### ISSUE TITLE
MPL-2.0 is compatibile with Apache-2.0

### ISSUE THREAD

**Issue by dpc** [Nemo157/cargo-lichking#14]
https://opensource.com/law/11/9/mpl-20-copyleft-and-license-compatibility

"Aligning these triggering conditions is what allowed us to be more comfortable that Apache 2.0 and MPL 2.0 are compatible."

**Comment by Nemo157** [comment]
Looks good to me, I'll add it soon. It also seems like there's _some_ sort of compatibility with having MPL-2.0 code included into a (MPL-2.0 OR GPL) project which can _then_ be included in a pure GPL project, but that's complicated enough I'm just going to ignore it for now.
