### ISSUE TITLE
list --long

### ISSUE THREAD

**Issue by blakehawkins** [Nemo157/cargo-lichking#16]
Would be nice to get license list in a way that's more immediately accessible for machine

Something like `cargo lichking list --long` which emits:

```
log-mdc : Any(MIT, Apache-2.0)
serde_derive : Any(MIT, Apache-2.0)
openssl_pkey : Apache-2.0
```

instead of 

```
Any(MIT, Apache-2.0): log-mdc, serde_derive
Apache-2.0: openssl_pkey
```

**Comment by Nemo157** [comment]
I like it :)

Not sure about the `--long` flag for it, I'll see if I can come up with an alternative. But the functionality would definitely be great to have.

**Comment by blakehawkins** [comment]
I'm not too fussed on the flag. Maybe `--verbose`?

**Comment by Nemo157** [comment]
0.5.2 should be published now. You can use `cargo lichking list --by crate` to list the license per crate.
