### ISSUE TITLE
thread-id has incompatible license

### ISSUE THREAD

**Issue by Nemo157** [Nemo157/cargo-lichking#2]
https://github.com/ruuda/thread-id is only licensed under `Apache-2.0` which fails the check as `cargo-lichking` is supposedly `Apache-2.0/MIT`. Does this actually matter at all? If so it probably matters a lot more for cargo itself since they are actually distributing binaries...

**Comment by est31** [comment]
thread-id seems to have been dual-licensed since: https://github.com/ruuda/thread-id/issues/5

I think this can be closed.

**Comment by Nemo157** [comment]
Cool, that's good. The new licensing is in 3.1.0+ metadata so I'll need to do an update before closing this, it's probably about time to bump the `cargo` version anyway so I'll try and do that over the weekend.

**Comment by RazrFalcon** [comment]
I've encountered the same problem with `openssl`:
```
error: cargo cannot include package openssl, license Apache-2.0 is incompatible with Any(MIT, Apache-2.0)
```
IANAL, but is they really incompatible?
