### ISSUE TITLE
New syntax for FSF licenses

### ISSUE THREAD

**Issue by kraai** [Nemo157/cargo-lichking#23]
According to https://www.gnu.org/licenses/identify-licenses-clearly.html, there will be a new syntax for FSF licenses:

* If the software is licensed only under a particular version of the license, the identifier is `LICENSE-VERSION-only` (e.g., `GPL-3.0-only`).
* If the software is licensed under a particular version of the license or any later version, the identifier is `LICENSE-VERSION-or-later` (e.g., `GPL-3.0-or-later`).

It would be nice if `cargo-lichking` supported this new syntax.

**Comment by Nemo157** [comment]
Sounds like a good idea, should be pretty simple to add.

**Comment by kraai** [comment]
Thanks!
