### ISSUE TITLE
list should sort dependencies by name

### ISSUE THREAD

**Issue by meltinglava** [Nemo157/cargo-lichking#59]
I had 134 packages with MIT / Apache 2.0 and wanted to just look fast for one. But it becomes a lot harder when the output is not sorted.

**Comment by meltinglava** [comment]
Looks like a strait forward issue to solve, and should be marked as good first issue. I might fix this next week if nobody takes it.

**Comment by Nemo157** [comment]
Yep, should be pretty easy to do, I'd happily accept a PR for it.
