### ISSUE TITLE
lichking does not support alternative registries

### ISSUE THREAD

**Issue by jrpascucci** [Nemo157/cargo-lichking#70]
Cargo lichking with configured alternative registries does not function.
> cargo lichking list
warning: IANAL: This is not legal advice and is not guaranteed to be correct.
error: failed to parse manifest at `C:\projects\cic\master\srv\jaims\validator\Cargo.toml`

Caused by:
  the cargo feature `alternative-registries` requires a nightly version of Cargo, but this is the `dev` channel

There is no alternative-registries feature any more, it's been stabilized at .34

(FYI: I'm poking around on how to bring it up to .41, which has lots of errors, but I have a problem in that I have to go through a corporate process before I would be allowed to do a pull request)

**Comment by Nemo157** [comment]
If .41 has enough breaking changes in the `cargo` API it may be time to switch to `cargo-metadata`, if it provides all the details needed.

That said, I'm tempted to start recommending using [`cargo-deny`](https://crates.io/crates/cargo-deny) and [`cargo-about`](https://crates.io/crates/cargo-about) instead and deprecate `cargo-lichking`.

**Comment by Nemo157** [comment]
I don't have anything I can test this with easily, but 0.9.0 is now using `cargo-metadata`, so as long as the underlying `cargo` it's calling into supports alternate registries it should work.
