### ISSUE TITLE
Open to large PRs?

### ISSUE THREAD

**Issue by sstadick** [Nemo157/cargo-lichking#79]
Hello!

I've been working on a [fork of `cargo-lichking`](https://github.com/sstadick/cargo-lichking/tree/refactor2) with the original intent of making a PR here with my changes. However, things have started to diverge a lot. Differences include:

- Full rewrite of `discovery.rs` and `bundle.rs`
- Many added templates and a few added licenses
- (soon) ability to serialize the thirdparty license texts to json or a text document similar to what is produced now
- (soon) ability to compare found licenses against an existing thirdparty file to check for changes / update changed sections
- Changed log levels so everything is not an error

Ideally I want a user to be able run `bundle`, inform them of missing licenses that they should add on their own, and then having something in CI that will check the THRIDPARTY file for changes over time.

If this sounds like more change than you are interested in OR you aren't interested in lots of activity happening here in the next month or so I intend to create a new project with a new name that solely focuses on the functionality in the bundle command, with proper attribution to `cargo-lichking`. It concerns me that the last commit to this project was over a  year ago and there are many open PRs and issues. At the moment I lean to creating a new thing to fit my needs / iterate quickly that won't encroach on the primary check functionality here. 

LMK your thoughts!

**Comment by Nemo157** [comment]
TBH I have been thinking of adding a deprecation notice and pointing users towards `cargo-deny` and `cargo-about` instead for a while. If you want to make a fork/alternative around the bundling aspect in particular then I could add that as another alternative in the list.

**Comment by sstadick** [comment]
I hadn't heard of either of those before! When I have an MVP I'll drop a link here :+1: 

Regardless of whether you deprecate this tool or not, thank you for working on it in the open in the first place!

**Comment by sstadick** [comment]
https://github.com/sstadick/cargo-bundle-licenses
